### ISSUE TITLE
[BUG] cannot level skills with greater than level 1 required

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#133] opened 2019-10-08 23:18 UTC
Version: NT-RPG 2.0.0-RC8
SpongeForge: spongeforge-1.12.2-2838-7.1.7-RC3928
Forge: 1.12.2-2838

Skills that require greater than level 1 to learn cannot be learned even if the character meets the requirements.

Steps to recreate:
Create a class and skilltree; within the skill tree have a skill with greater than level 1 required in order to learn. raise character to that level and attempt to learn the skill.
the chat will out put "you must be at least level `n` to learn this skill"

tests performed:
Attempted to learn a skill with only 1 class instead of multiple: same result as above.
Set class to Auto and leveled up to the required level: same result as above.

**Comment by NeumimTo** [comment] 2020-04-11 18:46
I cannot reproduce this issue anymore, neither on sponge nor spigot implementation.
Just to make it clear - Player starts any class at level 0. You need to level up to get to level 1. then you shall be able to learn the skill having MinPlayerLevel.

Maybe this was bug in the past and i fixed with some other change

**Closed by NeumimTo** 2020-04-11 18:46 UTC
Labels: Common

**Comment by hellbringer616** [comment] 2020-04-12 14:09
I'll retest when i have a bit more time; but the issue was the only level taken into account when factoring skill requirements was the primary class level defined in settings.conf

Example:
I am level 1 in Combat and level 11 in smithing, and trying to learn a level 7 skill in Smithing, i will not be high enough because combat is primary.
if i am level 11 in combat but level 1 in smithing i can learn the level 7 skill for the same reason.
