### ISSUE TITLE
[BUG] ASCII Map does not respect start location

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#99] opened 2019-02-21 15:31 UTC
When defining a "Start" location in an ASCII Map for skill trees regardless of where i put the X it always ends up starting in the upper most lefthand corner of the skilltree.

**Comment by NeumimTo** [comment] 2019-02-21 16:22
has this been happenning in the previous version as well?

**Comment by hellbringer616** [comment] 2019-02-21 17:11
It's been broken for quite a while yeah; since i think 1.0.11

**Comment by NeumimTo** [comment] 2019-02-24 21:06
This is intended behavior. 
Ascii Map Does respect the location of "X" but only for the first time you open it. 
After that you always open it on the point, where you closed it last time you had the skilltree open.

**Closed by NeumimTo** 2019-02-24 21:06 UTC
Labels: bug
